[package]
name = "data_validation_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
env_logger = "0.10"
log = "0.4"

[build-dependencies]
tonic-build = "0.8"
