# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocean_monitor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ocean_monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ocean_monitor.proto\x12\x0coceanmonitor\"^\n\x16\x44\x61taCalculationRequest\x12\x0f\n\x07wavy_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\xdd\x01\n\x17\x44\x61taCalculationResponse\x12\x0f\n\x07wavy_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x16\n\x0eoriginal_value\x18\x03 \x01(\x01\x12\x15\n\raverage_value\x18\x04 \x01(\x01\x12\x10\n\x08variance\x18\x05 \x01(\x01\x12\x19\n\x11trend_coefficient\x18\x06 \x01(\x01\x12\x18\n\x10normalized_value\x18\x07 \x01(\x01\x12\x15\n\ranomaly_score\x18\x08 \x01(\x01\x12\x11\n\ttimestamp\x18\t \x01(\x03\x32y\n\x16\x44\x61taCalculationService\x12_\n\x10\x43\x61lculateMetrics\x12$.oceanmonitor.DataCalculationRequest\x1a%.oceanmonitor.DataCalculationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocean_monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATACALCULATIONREQUEST']._serialized_start=37
  _globals['_DATACALCULATIONREQUEST']._serialized_end=131
  _globals['_DATACALCULATIONRESPONSE']._serialized_start=134
  _globals['_DATACALCULATIONRESPONSE']._serialized_end=355
  _globals['_DATACALCULATIONSERVICE']._serialized_start=357
  _globals['_DATACALCULATIONSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
